### ISSUE TITLE
是否有方式可以实现强制下载的分片文件在网页中当缓存文件播放？

### ISSUE THREAD

**Issue by y11255** [Momo707577045/m3u8-downloader#1]
是否有方式可以实现强制下载的分片文件在网页中当缓存文件播放？

**Comment by Momo707577045** [comment]
分情况，支持 ts 格式播放器的浏览器可以。
之前有试过，mac 自带 ts 格式播放，mac 上用 chrome 可以直接播放。
但由于不是主流功能，不想因此增加工具复杂度。加大源码阅读成本，没有去实现
