### ISSUE TITLE
被AES加密的，提示AES配置不正确怎么破

### ISSUE THREAD

**Issue by fffk3045167** [Momo707577045/m3u8-downloader#10]
太难了

**Comment by fffk3045167** [comment]
而且注入代码后，工具栏也没有显示在底部

**Comment by Momo707577045** [comment]
是特定网站定制化问题，有兴趣可以加一下作者QQ，提供详细信息给你解答

**Comment by fffk3045167** [comment]
这个搞起来复杂吗，我看好多都是AES加密的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Momo707577045/m3u8-downloader"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月21日(星期四) 上午10:23
收件人:&nbsp;"Momo707577045/m3u8-downloader"<m3u8-downloader@noreply.github.com&gt;;
抄送:&nbsp;"无可心"<1095983267@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Momo707577045/m3u8-downloader] 被AES加密的，提示AES配置不正确怎么破 (#10)





 
是特定网站定制化问题，有兴趣可以加一下作者QQ，提供详细信息给你解答

**Comment by Momo707577045** [comment]
再试试，已修复跨域注入后的 AES 解密问题
