### ISSUE TITLE
在network里找不到m3u8的链接

### ISSUE THREAD

**Issue by 532643588** [Momo707577045/m3u8-downloader#11]
按照步骤找到网页中F12-network-但是在下面没有找到有m3u8的链接，只有ts文件。
请问怎么找到m3u8的链接呢？
谢谢
更新：已经找到了链接，但是那个链接并不是m3u8结尾的，而是很长一段，我看到网上有人把那段链接转换了一下得到了以m3u8结尾的链接就可以了，请问有什么办法可以得到可用的m3u8链接吗？
![1609705046(1)](https://user-images.githubusercontent.com/76918751/103487925-b8a94680-4e00-11eb-9991-ac635a8eece8.png)

**Comment by L1yp** [comment]
这个就是M3U8结尾的文件，只不过后面带了参数

**Comment by Momo707577045** [comment]
楼上正确，多谢帮忙回复
