### ISSUE TITLE
跨域好难受，注入了也不行

### ISSUE THREAD

**Issue by po888375** [Momo707577045/m3u8-downloader#12]
注入了console里显示
![1](https://user-images.githubusercontent.com/42614393/103546693-60487680-4ede-11eb-8991-f4779363f83d.png)

**Comment by wzdlagrange** [comment]
你是选择了MP4格式吧？
你选原格式试试？
我MP4格式也报这个错误，原格式没问题

**Comment by Momo707577045** [comment]
收到，应该是个 bug，新加的资源未考虑跨域情况，我稍后加上去。多谢反馈，多谢帮忙回答

**Comment by Momo707577045** [comment]
已修复
