### ISSUE TITLE
怎么对抗反调试的网页

### ISSUE THREAD

**Issue by L1yp** [Momo707577045/m3u8-downloader#13]
v.qq.com

**Comment by wzdlagrange** [comment]
谷歌浏览器 右上角的 × 下面 有 三个点
三个点->更多工具->开发者工具
这样就行了

**Comment by Momo707577045** [comment]
qq 等主要视频网站，添加了定制化加密，本工具不注册。另外，本工具仅供学习，尊重版权，不做定向破解。
