### ISSUE TITLE
只能播放一点

### ISSUE THREAD

**Issue by wdShuo** [Momo707577045/m3u8-downloader#18]
下载TS片 到 合成 mp4都没有问题，但是播放下载mp4文件的时候，只能播放前几秒，然后视频就不动了，但是进度还在走：画面静止，但是下面的视频进度一直在走。 请问 这个是什么问题，在使用Blob把TS转成MP4的时候 需要加什么参数吗？
--注：刚才看了一样例子 就是31秒，我的视频是15分钟的也只能播放30秒左右，就不能播放了。是不是这个就是这个程序的限制呢？

**Comment by Momo707577045** [comment]
http://dev-n-tianchi-oss.oss-cn-beijing.aliyuncs.com/record/live/22017100020000000001/22017100020000000001_1253_2020-12-20-23-49-29.m3u8
无法复现，作者这边能正常下载，正常播放。初步估计是播放器问题。建议换个播放器播放

**Comment by Momo707577045** [comment]
问题已复现，是进行 mp4 转码时，特定视频编码方式不兼容导致的。
短时间无法解决，可使用原格式下载，不进行 mp4 转码暂时规避该问题。
