### ISSUE TITLE
English Documentation

### ISSUE THREAD

**Issue by jhemmmm** [Momo707577045/m3u8-downloader#22]

**Comment by Momo707577045** [comment]
Sorry, I'm too busy to reply late.
This is the English version of the page, the English version of the document will be added later
http://blog.luckly-mjw.cn/tool-show/m3u8-downloader/index-en.html

**Comment by Momo707577045** [comment]
The English document has been completed. Thank you for your attention
https://github.com/Momo707577045/m3u8-downloader/blob/master/README-EN.md

**Comment by jhemmmm** [comment]
Thanks.
