### ISSUE TITLE
一个例子，下载的视频完整，但声音混乱

### ISSUE THREAD

**Issue by uptonking** [Momo707577045/m3u8-downloader#23]
对于 [这个m3u8实例文件(是530MB的视频)](https://youku.cdn-56.com/20180326/QoZNqLbG/800kb/hls/index.m3u8),
用本项目的在线工具下载的mp4，视频完整，但声音大部分确实且混乱，
用 https://github.com/HeiSir2014/M3U8-Downloader 这个工具下载的视频声音就是完整的，
原因我也不清楚

**Comment by Momo707577045** [comment]
好的，我抽时间看看，多谢反馈

**Comment by Momo707577045** [comment]
测了一下，问题未能复现。可能是特定机制的编码问题。感谢反馈
