### ISSUE TITLE
Uncaught ReferenceError: AESDecryptor is not defined

### ISSUE THREAD

**Issue by yuxia5454** [Momo707577045/m3u8-downloader#24]
Uncaught ReferenceError: AESDecryptor is not defined
    at Object.success (<anonymous>:588:40)
    at XMLHttpRequest.xhr.onreadystatechange (<anonymous>:485:40)
跨域注入后显示

**Comment by Momo707577045** [comment]
暂无复现，刷新工具页面试试？这个问题之前解决过了。
还不行的话，方便贴一下目标网站吗？我本机试试

**Comment by wangwenwwx** [comment]
可能是因为脚本地址是http的，被浏览器拦截了，改成https就好了。
![image](https://user-images.githubusercontent.com/26155919/172642345-951fcbba-263b-4963-8224-78acb228f295.png)
