### ISSUE TITLE
English Version

### ISSUE THREAD

**Issue by YssDiamond** [Momo707577045/m3u8-downloader#25]
Hello momo i would love to try your m3u8 downloader is there a english version that i could use? thanks in advance

**Comment by Sciroccogti** [comment]
Maybe duplicate of #22 ?

**Comment by YssDiamond** [comment]
what i mean is the program interface but i guess it's only in chinese

**Comment by Sciroccogti** [comment]
> what i mean is the program interface but i guess it's only in chinese

http://blog.luckly-mjw.cn/tool-show/m3u8-downloader/index-en.html

You should check this mentioned [here](https://github.com/Momo707577045/m3u8-downloader/issues/22#issuecomment-785888922)~

**Comment by YssDiamond** [comment]
Alright thanks this can be closed
