### ISSUE TITLE
不能在线解码aes可太难了

### ISSUE THREAD

**Issue by thenextsupersun** [Momo707577045/m3u8-downloader#3]
页面注入解码不了，本地能解码解决不了跨域，我太难了

**Comment by Momo707577045** [comment]
收到，多谢反馈，我看看页面注入后的解码问题。完成后给你留言

**Comment by Momo707577045** [comment]
已修复该问题，多谢反馈

**Comment by crashiers** [comment]
没解密功能？

**Comment by Momo707577045** [comment]
> 没解密功能？

已再次修复该问题，多谢反馈

**Comment by llychao** [comment]
> 页面注入解码不了，本地能解码解决不了跨域，我太难了

看看这个，三端直接运行：https://github.com/llychao/m3u8-downloader
