### ISSUE TITLE
网站禁止f12，油猴也用不了，太难了

### ISSUE THREAD

**Issue by liumuyv** [Momo707577045/m3u8-downloader#30]

**Comment by Momo707577045** [comment]
附上目标示例网站哈，可以学习一下

**Comment by yilmazdurmaz** [comment]
1- dont just press F12, follow menu->tools->developer tools
2- some sites allergic to devtools, and remove video content if you open it. check this out to intercept [WebRequestExample](https://github.com/donhatch/chromeWebRequestExample).

however, dont just blindly install it. it is not a fully functional tool. it will intercept all of your pages. disable it every time your work is done with it.
