### ISSUE TITLE
m3u8文件内容非ts文件而是image文件

### ISSUE THREAD

**Issue by yiliufeng168** [Momo707577045/m3u8-downloader#31]
我在某视频解析网站查看其m3u8文件内容为以下格式
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:9
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:6.208,
https://p1.pstatp.com/img/tos-cn-i-0000/e5bc52b70e6440f1b6a65f71b8f27fa5~tplv-obj.image
#EXTINF:6.25,
https://p1.pstatp.com/img/tos-cn-i-0000/9cfd9f4eacd44003acccd61f77a3bc83~tplv-obj.image
#EXTINF:6.208,
该文件与ts文件相似只要修改后缀名即可

**Comment by yilmazdurmaz** [comment]
check this issue #32 on how I manually download-combine them.

**Comment by Momo707577045** [comment]
已兼容
