### ISSUE TITLE
redownloading false fragmentation is bugged

### ISSUE THREAD

**Issue by yilmazdurmaz** [Momo707577045/m3u8-downloader#33]
it might be only visual but if there are more than 1 error, clicking on redownload button causes more fragment boxes than before to appear. and in some cases does not start redownloading.

**Comment by Momo707577045** [comment]
Thank you. Is it convenient to attach a download link? I'll try to reproduce the bug

**Comment by yilmazdurmaz** [comment]
@Momo707577045 
As server error causing this is not always happening, random 3-5 error in 1000 fragments, and they are not persistent, it is hard to produce this bug. unfortunately, I don't know how to make this kind of throttling/timed-out response. maybe comparing the changes you made to part running after pressing "redownload" button to previous versions (at least 1-2 months ago it was fine) will show a way to bugging code.

meanwhile trying to test this maybe-visual bug, related or not I have stumbled upon another bug, should I report it in another post? :

I tried to make a few-file-m3u8 and purposely renamed a fragment file so as to make it missing and not to be found. it is unfortunate that your extension did not register this "missing file" as an error and downloaded all others then combined to give an ill-fated compilation. (I haven't tried this in old versions to see if it is a bug with new version)

**Comment by yilmazdurmaz** [comment]
@Momo707577045 

an important question before continuing our discussion:

is it yours or are you a part of this Chrome extension: [m3u8 online video extractor](https://chrome.google.com/webstore/detail/m3u8-online-video-extract/fcpefnjbneopahdnhdhahbhoccipdmdm)

because I use this one and on MS-Edge, and it would not be a fruitful discussion if that extension is going in a different path than you follow.

**Comment by Momo707577045** [comment]
I haven't found any bugs caused by redownloading yet. It may be a small probability event

**Comment by Momo707577045** [comment]
That plug-in is not my work. Thank you very much for your feedback. You are really a warm-hearted guy
