### ISSUE TITLE
audio issue after saved as mp4, distortion, breaking, muted...

### ISSUE THREAD

**Issue by billson-my** [Momo707577045/m3u8-downloader#34]
Tested target
https://17-cdn.savingbox.me/content/dy-tkyl-hd-20210503-01.mp4/index.m3u8

1st day using experience...
tried 1st file with 994MB
used time: ~ 32 minutes.
started on: 9:10pm
completed on: 9:42pm

**Comment by Momo707577045** [comment]
Ok, I will try it

**Comment by Momo707577045** [comment]
The problem has been fixed. My computer test is normal. Thank you for your feedback
