### ISSUE TITLE
只有TS没有M3U8怎么破？

### ISSUE THREAD

**Issue by 775405984** [Momo707577045/m3u8-downloader#38]
[这个网站](https://appas1iun483298.h5.xiaoeknow.com/v1/course/video/v_609c97f0e4b0fe322012c19b?type=2&pro_id=p_5f7063a6e4b0d59c87b8b5d4&is_redirect=1) (可能需要微信登录)在播放时，没有m3u8，而且下载的ts文件也是不可播放的，难道是加密了吗？
请问找没找到这个m3u8文件？

**Comment by Momo707577045** [comment]
经测试，m3u8 链接应该是这个，https://appas1iun483298.h5.xiaoeknow.com/video_encrypt/index?m3u8=axHiRa0oceD_ovviLdzeEoy_NeTnIc1rMyjpQtx_MwjhYiurdlmy9_kiMsi_5at_elXiFajnbgGz9a1iZC5jb20vOTc2NGE3YTV2b2R0cmFuc2d6cDEyNTI1MjQxMjYvYmFiYmQ1OGU1Mjg1ODkwODE4MjkyMTQyMjY3L2RybS92LmY0MjEyMjAubTN1OAO0O0OO0O0O
但该网站进行了定制化加密，不可通过通用性方法解密
