### ISSUE TITLE
油猴插件链接已失效

### ISSUE THREAD

**Issue by isPoto** [Momo707577045/m3u8-downloader#43]
油猴插件已被删除

**Comment by Vangelis66** [comment]
Not only 
https://greasyfork.org/scripts/422237-m3u8-downloader
was **deleted**, but, apparently, also dependencies
https://greasyfork.org/scripts/426404-aes-decryptor-js
https://greasyfork.org/scripts/427821-百度统计

**Existing** installations of the userscript were pushed **update 0.4.3.1**, which **deleted** previous version... :-1: 
What gives? :angry:

**Comment by Momo707577045** [comment]
因平台审核较为严格，无力维护，已从平台撤销。
现添加了「手动添加油猴插件」教程，通过简单的代码粘贴复制即可复现该脚本
https://github.com/Momo707577045/m3u8-downloader#%E6%B2%B9%E7%8C%B4%E6%8F%92%E4%BB%B6

**Comment by Vangelis66** [comment]
> Due to stricter platform audits and the inability to further maintain it, the userscript was withdrawn from the platform (greasyfork.org).
> Added now the "Manually add Greasemonkey plug-in" tutorial; the userscript can be installed by a simple code copy-paste: 
> 
> https://github.com/Momo707577045/m3u8-downloader#油猴插件

Thanks for your kind reply and provided solution :+1: 
My **userscript manager** of choice is the open-source **[ViolentMonkey](https://github.com/violentmonkey/violentmonkey)** extension, I was able to install the new userscript easily, via the "**install script from URL**" option: 
```
https://github.com/Momo707577045/m3u8-downloader/raw/master/tamper-monkey.js
```
![momo](https://user-images.githubusercontent.com/9669492/127174810-cf7bb086-728b-4aa7-aa4e-79f3569e455c.jpg)

Best wishes :smiley:

**Comment by zhangsean** [comment]
#51 游候脚本以.user.js结尾，在浏览器查看Raw源码就会自动弹出脚本安装界面
