### ISSUE TITLE
下载视频后视频乱码 

### ISSUE THREAD

**Issue by nianwu** [Momo707577045/m3u8-downloader#44]
m3u8地址: https://dh5.cntv.lxdns.com/asp/h5e/hls/1200/0303000a/3/default/b7a1d4a8c0c24322b945d9d75bec3ee6/1200.m3u8

**Comment by Momo707577045** [comment]
初步估计是该视频做了定制化加密，导致视频不可用

**Comment by nianwu** [comment]
应该不是视频加密所致
我这样试过:
使用 ffmpeg 下载 [m3u8文件地址](https://newcntv.qcloudcdn.com/asp/hls/main/0303000a/3/default/34c76df444bf4812b39f542c09ff481f/main.m3u8?maxbr=2048) , 合并出来的文件是可以正常播放的
使用 ffmpeg 下载 其中的 [1200m3u8文件](https://newcntv.qcloudcdn.com/asp/hls/1200/0303000a/3/default/34c76df444bf4812b39f542c09ff481f/1200.m3u8) 合并出来无法播放

我看到其他的 issue 中也提到了, 不支持如下格式: 

```text
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=460800, RESOLUTION=480x270
/asp/hls/450/0303000a/3/default/34c76df444bf4812b39f542c09ff481f/450.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=870400, RESOLUTION=640x360
/asp/hls/850/0303000a/3/default/34c76df444bf4812b39f542c09ff481f/850.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1, BANDWIDTH=1228800, RESOLUTION=1280x720
/asp/hls/1200/0303000a/3/default/34c76df444bf4812b39f542c09ff481f/1200.m3u8
```

既然 ffmpg 可以合并出来 可以播放的视频, 那么应该不是加密导致
@Momo707577045

**Comment by Momo707577045** [comment]
收到，感谢反馈，问题我记录一下，晚点看看
