### ISSUE TITLE
建议增加自定义header功能

### ISSUE THREAD

**Issue by okadwin** [Momo707577045/m3u8-downloader#49]
有些网站为了防采集可能会验证header中的referer或其他自定义的头信息，建议增加自定义请求头的功能。

**Comment by Momo707577045** [comment]
感谢建议，该功能使用门槛较高，会增长交互复杂度，暂不增加哈。
但这个建议很棒，可以 fork 进行二次开发，这也正是本项目的初衷之一
“本工具运用到的都只是 JS 的常见知识，并不复杂。鼓励大家多尝试阅读源码，其实看源码并没有想象中的那么困难。”
