### ISSUE TITLE
m3u8文件格式问题

### ISSUE THREAD

**Issue by howbbig** [Momo707577045/m3u8-downloader#5]
#EXT-X-KEY:METHOD=AES-128,URI="https://app.xiaoe-tech.com/get_video_key.php?edk=CiCZaCl4MgXoSZGRx6wbmEaNnSVqtG8ka9tEjdWgZ1tqzBCO08TAChiaoOvUBCokYjRhNjFiNTgtMmVhNy00OWYxLTgwZGMtZTE0NTIyODc5YWIy&fileId=5285890807766263456&keySource=VodBuildInKMS",IV=0x00000000000000000000000000000000
#EXTINF:10.000000,
v.f100230.ts?start=0&end=671167&type=mpegts

你好，请问这种格式的m3u8可以下载吗？工具好像下不动。。

**Comment by Momo707577045** [comment]
具体m3u8 地址是什么？

**Comment by howbbig** [comment]
> 具体m3u8 地址是什么？

https://1252524126.vod2.myqcloud.com/9764a7a5vodtransgzp1252524126/e96026f65285890807766263456/drm/v.f100230.m3u8?time=1600772656265
就这个地址，麻烦了。

**Comment by Momo707577045** [comment]
抱歉，工作忙，才有时间回复。
这是个程序上的 Bug，现已修复，感谢反馈
