### ISSUE TITLE
cableav.tv 的视频无法下载

### ISSUE THREAD

**Issue by learn2021-coder** [Momo707577045/m3u8-downloader#55]
大佬好：

https://cableav.tv/cjkwYuVN80p/
这个网站的视频，观看超过一段时间之后（5分钟左右），就不能继续观看了，
下载也一样，下载到一定的比例（20%-30#）服务器就会拒绝连接，导致下载失败。不知道是服务器故意这样做的还是我的操作有问题。

**Comment by Momo707577045** [comment]
该网站本身已无法播放，无法测试问题。
若仍存在问题，请附上最新视频地址

**Comment by bot223** [comment]
最大进程不要超过10即可，我已经用这个下载了2年了
