### ISSUE TITLE
开启油猴脚本会使B站和个人用户相关的按钮和功能全部消失

### ISSUE THREAD

**Issue by HJXArthurAtlas** [Momo707577045/m3u8-downloader#57]
# 开启油猴脚本会使B站和个人用户相关的按钮和功能全部消失

- 浏览器：Chrome 96.0.4664.45

- 油猴版本：4.13

- 脚本版本：0.5.0

    > 在油猴中开启脚本后，打开B站后本来应该显示在页面右上角的“头像、大会员、消息、动态、收藏、历史、创作中心”按钮会直接消失，并且直接地址栏访问个人动态页面时也会无法加载。

![image-20211120113316874](https://gitee.com/arthuratlas/drawing-bed/raw/master/202111201133190.png)

![image-20211120113743559](https://gitee.com/arthuratlas/drawing-bed/raw/master/202111201137855.png)

**Comment by BlingRbt** [comment]
对的 我也发现了这个问题
好像是B站检测所有关于调速下载的插件
检测到就会不显示个人相关信息......好蛋疼

**Comment by Momo707577045** [comment]
是的，B 站做了特定防御，且 B 站底层做了定制化加密，无法使用本工具提取。
已在最新的油猴插件中，忽略对 B 站的检测，感谢反馈。
