### ISSUE TITLE
下载ts文件时候一直提示“失败-系统繁忙”

### ISSUE THREAD

**Issue by jasondong1999** [Momo707577045/m3u8-downloader#60]
我用注入方式加载下点击原格式下载，加载一些顺利，进行到100%后自动下载，提示”失败-系统繁忙“，点击强制下载现有片段也是这个提示，视频文件大概2G左右，这是什么原因啊，怎么处理

**Comment by Momo707577045** [comment]
这个问题这边没遇到过哦，方便贴一下目标视频网站，以便复现问题吗
