### ISSUE TITLE
用ajax拉m3u8会触发跨域

### ISSUE THREAD

**Issue by autulin** [Momo707577045/m3u8-downloader#63]
有的网站会有跨域的问题，考虑怎么解决一下

**Comment by llychao** [comment]
> 有的网站会有跨域的问题，考虑怎么解决一下

看看这个，三端直接运行，多线程，下载速度超出你的想象：https://github.com/llychao/m3u8-downloader

**Comment by Momo707577045** [comment]
可以通过代码注入的方式，或者油猴插件，自动拦截，自动注入的方式绕过跨域问题
点击这个链接，安装油猴插件，

https://blog.luckly-mjw.cn/tool-show/m3u8-downloader/m3u8-downloader.user.js
--
