### ISSUE TITLE
tv.cctv.com 站点做了加密吗

### ISSUE THREAD

**Issue by Sauvio** [Momo707577045/m3u8-downloader#64]
在tv.cctv.com站点下载视频，在本地播放，视频全屏马赛克。

**Comment by orestonce** [comment]
看这个帖: https://tieba.baidu.com/p/7182547058

**Comment by Momo707577045** [comment]
欢迎使用「无差别视频下载工具」，无视加密编码问题，
https://segmentfault.com/a/1190000025182822
