### ISSUE TITLE
遇到个牛批网站在播放页F12就卡死让你重启浏览器

### ISSUE THREAD

**Issue by SelectSex** [Momo707577045/m3u8-downloader#65]
https://www.nnyy6.top/dianying/

这个网站的伦理片都是AES加密的，跨域无法下载，只能注入到当前页面，但是注入就会卡死，除非我自己本地替换他的Js，那就太麻烦了

**Comment by llychao** [comment]
> https://www.nnyy6.top/dianying/
> 
> 这个网站的伦理片都是AES加密的，跨域无法下载，只能注入到当前页面，但是注入就会卡死，除非我自己本地替换他的Js，那就太麻烦了

看看这个，三端直接运行，不依赖浏览器：https://github.com/llychao/m3u8-downloader

**Comment by Momo707577045** [comment]
建议使用配套的油猴插件完成视频的识别与下载，无需手动注入代码。一键完成。
访问以下网站，安装油猴插件


https://blog.luckly-mjw.cn/tool-show/m3u8-downloader/m3u8-downloader.user.js
--
