### ISSUE TITLE
两种方法均无法下载

### ISSUE THREAD

**Issue by bian2022** [Momo707577045/m3u8-downloader#68]
点“跳转下载”无反应，点“注入下载”，提示“注入成功，请滚动到页面底部”,
![image](https://user-images.githubusercontent.com/101516281/170487828-fe745834-3c17-4efe-b16e-22ac58066d81.png)
并出现这个，但网页底部并没有，希望作者能解决一下，谢谢！
注：由于涉及到18+内容（你懂的），我不能直接公布链接，希望作者能提供个联系方式，或联系我的邮箱20220526github@zhuce2022.uu.me

**Comment by bian2022** [comment]
？？？

**Comment by orestonce** [comment]
试试我这个呢  https://github.com/orestonce/m3u8d

**Comment by Momo707577045** [comment]
@bian2022 已邮件私聊，欢迎反馈问题

**Comment by bian2022** [comment]
> 试试我这个呢 https://github.com/orestonce/m3u8d

关键我不知道m3u8啊

**Comment by bian2022** [comment]
> @bian2022已发邮件私聊，欢迎回复问题

OK

**Comment by Momo707577045** [comment]
「点击跳转」没反应问题，是该网站对 window.open 函数进行了改写。
问题已解决，本地测试通过，点击以下链接完成插件更新，重试即可
https://blog.luckly-mjw.cn/tool-show/m3u8-downloader/m3u8-downloader.user.js
