### ISSUE TITLE
添加脚本后使用失败

### ISSUE THREAD

**Issue by a1b2d3c** [Momo707577045/m3u8-downloader#69]
es1int: userscripts/better-use-match - Using @include is potentially unsafe andmay be obsolete in Manifest v3 in early 2023. P1ease switch to match.

本人小白，不是计算机专业人士，请求解决问题，谢谢您！

**Comment by Momo707577045** [comment]
这只是个提示，意思是 @include 这个指令在后续可能不被支持了，建议替换成 match 实现该功能。
无视该提示就好，插件的功能还是能正常使用的
