### ISSUE TITLE
多个EXT-X-KEY

### ISSUE THREAD

**Issue by rtyuy** [Momo707577045/m3u8-downloader#7]
请教下 类似这种多个key的是什么解密逻辑？ 
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="data:text/plain;base64,AAAASnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAACoSEFSpCo7bLctFQFF8rssCiMoSEFSpCo7bLctFQFF8rssCiMpI88aJmwY=",KEYID=0x54A90A8EDB2DCB4540517CAECB0288CA,IV=0xCEB45439F229097D77E6FE412A6D8DEA,KEYFORMATVERSIONS="1",KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://54a90a8edb2dcb4540517caecb0288ca",KEYFORMATVERSIONS="1",KEYFORMAT="com.apple.streamingkeydelivery"

**Comment by Momo707577045** [comment]
这是定制化内容，本工具暂无涉及，感谢提问。
