### ISSUE TITLE
请问油猴插件版的文件名可以改成视频标题吗？现在下载的视频标题是当前的时间

### ISSUE THREAD

**Issue by XTLdirector** [Momo707577045/m3u8-downloader#70]

**Comment by Momo707577045** [comment]
好想法，我想想怎么实现，感谢建议

**Comment by Momo707577045** [comment]
该功能已实现，点击下方链接重新安装油猴插件，页面缓存重新加载即可
https://blog.luckly-mjw.cn/tool-show/m3u8-downloader/m3u8-downloader.user.js
