### ISSUE TITLE
优酷，提取m3u8链接之后无法下载

### ISSUE THREAD

**Issue by 0519-Echo** [Momo707577045/m3u8-downloader#72]
控制台提取到的链接如下：
https://pl-ali.youku.com/playlist/m3u8?vid=XMTgyNTI2NjAxNg%3D%3D&type=hd2&ups_client_netip=b78fe4e5&utid=2UCuGo9DOzQCASebjd6oZJSv&ccode=0502&psid=c9efaffe5bf245bdcb33ccb8db0aad0a41346&ups_userid=944513732&ups_ytid=944513732&app_ver=4.1.6&duration=1506&expire=18000&drm_type=1&drm_device=7&drm_default=1&nt=1&media_type=standard%2Csubtitle&dyt=1&ups_ts=1660724716&onOff=16&encr=0&ups_key=1ba5122075e4a09cd0a611f2d30d883f&ckt=5&m_onoff=0

另，这个链接使用另外一个插件
chrome-extension://pibnhedpldjakfpnfkabbnifhmokakfb/options.html
可以下载
但是mp4转码下载后硬解会黑屏，软解会音画不同步卡顿，并且下载下来之后本地文件的时间很奇怪（如图）。。。
![image](https://user-images.githubusercontent.com/104153307/185073484-adcc9d33-437a-4d45-87be-f030ee3a5e8c.png)

下ts又要转，唉。请问大佬是youku的问题吗

**Comment by Momo707577045** [comment]
优酷等主流视频网站都对 m3u8 视频做了定制性加密，如需下载，可改用 [无差别视频提取工具](https://segmentfault.com/a/1190000025182822) 实现
