### ISSUE TITLE
脚本注入不能开始下载，但手动注入可以下载。

### ISSUE THREAD

**Issue by LIMTANX** [Momo707577045/m3u8-downloader#74]
注入，提取链接，aes解码都没问题，但是点了开始下载后停住了。不过我手动注入，手动输入链接，是可以开始下载的。

**Comment by Momo707577045** [comment]
方便留一下网站地址吗？我本地复现看看是什么问题

**Comment by LIMTANX** [comment]
我找了个类似的，这个网址有同样的问题：
https://app80cx1dod4392.h5.xiaoeknow.com/p/course/column/p_5e54ef881fff4_A3F2SBxs?type=3

还有好奇问一下，下面这个网站的视频会下载错误，这是不是就是定制加密？
https://xueyuan.xiaoe-tech.com/detail/v_6164ffb6e4b038442e0a9777/3

**Comment by LIMTANX** [comment]
// 加载 ASE 解密
let $ase = document.createElement('script')
$ase.src = 'https://blog.luckly-mjw.cn/tool-show/m3u8-downloader/aes-decryptor.js'

我把上面这串代码里面的链接换成了'https://upyun.luckly-mjw.cn/lib/aes-decryptor.js'，发现可以开始下载了，不过页面排版有点怪。

**Comment by Momo707577045** [comment]
Hello，你好，详细看了下，该网站在视频资源中添加了自己的业务逻辑，可以理解为做了定制性的加密，无法通过本工具进行通用性提取。
如需提取，可考虑使用「无差别视频提取工具」完成下载。
https://segmentfault.com/a/1190000025182822
