### ISSUE TITLE
ts视频下载中之后没反应

### ISSUE THREAD

**Issue by kusila** [Momo707577045/m3u8-downloader#82]
![9D540D76-2FFE-4431-8B36-0626CF3C4D47](https://user-images.githubusercontent.com/28586954/192476934-1fcffa8b-30f4-4ab0-b51b-c5e4fbb7bce8.png)
![image](https://user-images.githubusercontent.com/28586954/192477245-b8d20862-bfe2-4f91-b150-bd361ac6ec0e.png)
![9647732C1A20BF524C6E5FAD8D65909E](https://user-images.githubusercontent.com/28586954/192477010-dbb11e38-3c12-4287-8287-2e827c9724f5.jpg)

**Comment by Momo707577045** [comment]
麻烦留一下 m3u8 地址，我这边复现看一下

**Comment by kusila** [comment]
https://play.qiqiuyun.net/sdk_api/video/hls_stream/sd.m3u8?resNo=cf5e9390005b47a6b8cc5ef971927c31&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsZXZlbCI6InNkIiwicHJldmlldyI6bnVsbCwicGxheUF1ZGlvIjowLCJoZWFkIjoiOGRiMWE0MjY5ZmIyNDIxYzkyODA5ZmEwODgzOTA4ZjciLCJza2lwIjpudWxsLCJubyI6ImNmNWU5MzkwMDA1YjQ3YTZiOGNjNWVmOTcxOTI3YzMxIiwianRpIjoiYjViOWY4NWMtYTNlMi00ZiIsInRpbWVzIjoxLCJleHAiOjE2NjQzNzgyMjQsImVuY3J5cHQiOjIsIm5hdGl2ZSI6MCwiaGxzQ2xlZkVuY3J5cHRWZXJzaW9uIjozfQ.vgOKspMYcKmyx3ggRnSSSUCN0gRuuUiLqnoFZLH9uEE&ssl=1

**Comment by kusila** [comment]
部分返回：
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:20
#EXT-X-ALLOW-CACHE:YES
#EXT-X-MEDIA-SEQUENCE:0

#EXT-X-KEY:METHOD=AES-128,URI="https://play.qiqiuyun.net/sdk_api/video/hls_clef/sd?resNo=8db1a4269fb2421c92809fa0883908f7&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsZXZlbCI6InNkIiwicGxheUF1ZGlvIjpudWxsLCJubyI6IjhkYjFhNDI2OWZiMjQyMWM5MjgwOWZhMDg4MzkwOGY3IiwianRpIjoiYTljYWE5ZDktMjQ5ZC00ZSIsInRpbWVzIjoxLCJleHAiOjE2NjQzNjM4MjQsImVuY3J5cHQiOjIsIm5hdGl2ZSI6MCwiaGxzQ2xlZkVuY3J5cHRWZXJzaW9uIjozfQ.CqVG9N4iie_j1WIfMWfPHOFYtyYqIKAXxOHB614CauY&ssl=1",IV=0x3307e1576f8353b27314cadb450416dc
#EXTINF:9.800,
https://ese3a9b6c5d0ic-pub.pubssl.qiqiuyun.net/39650/8db1a4269fb2421c92809fa0883908f7/ltekfHYi_bNIpSF2-merged-sd_seg_0_ehls_a5de49?schoolId=39650&fileGlobalId=cf5e9390005b47a6b8cc5ef971927c31
#EXT-X-DISCONTINUITY
#EXT-X-KEY:METHOD=AES-128,URI="https://play.qiqiuyun.net/sdk_api/video/hls_clef/sd?resNo=cf5e9390005b47a6b8cc5ef971927c31&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsZXZlbCI6InNkIiwicGxheUF1ZGlvIjpudWxsLCJubyI6ImNmNWU5MzkwMDA1YjQ3YTZiOGNjNWVmOTcxOTI3YzMxIiwianRpIjoiNzljMTMyZTYtOTI1YS00MiIsInRpbWVzIjoxLCJleHAiOjE2NjQzNjM4MjQsImVuY3J5cHQiOjIsIm5hdGl2ZSI6MCwiaGxzQ2xlZkVuY3J5cHRWZXJzaW9uIjozfQ.-K3v_ZMMzLPjd2Lmu3geP-b9NEj-KvbyPNAY4MMDZps&ssl=1",IV=0x0b168561aad4bcd2b24da90f34d23d56
#EXTINF:10.100,
https://ese3a9b6c5d0ic-pub.pubssl.qiqiuyun.net/39650/cf5e9390005b47a6b8cc5ef971927c31/ljpioMlOykKFpOC1-merged-sd_seg_0_ehls_f843e9?schoolId=39650&fileGlobalId=cf5e9390005b47a6b8cc5ef971927c31
#EXT-X-KEY:METHOD=AES-128,URI="https://play.qiqiuyun.net/sdk_api/video/hls_clef/sd?resNo=cf5e9390005b47a6b8cc5ef971927c31&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsZXZlbCI6InNkIiwicGxheUF1ZGlvIjpudWxsLCJubyI6ImNmNWU5MzkwMDA1YjQ3YTZiOGNjNWVmOTcxOTI3YzMxIiwianRpIjoiNzljMTMyZTYtOTI1YS00MiIsInRpbWVzIjoxLCJleHAiOjE2NjQzNjM4MjQsImVuY3J5cHQiOjIsIm5hdGl2ZSI6MCwiaGxzQ2xlZkVuY3J5cHRWZXJzaW9uIjozfQ.-K3v_ZMMzLPjd2Lmu3geP-b9NEj-KvbyPNAY4MMDZps&ssl=1",IV=0x19b91e51053c69879383a5dc092fb13e
#EXTINF:10.000,
https://ese3a9b6c5d0ic-pub.pubssl.qiqiuyun.net/39650/cf5e9390005b47a6b8cc5ef971927c31/ljpioMlOykKFpOC1-merged-sd_seg_1_ehls_b16ad8?schoolId=39650&fileGlobalId=cf5e9390005b47a6b8cc5ef971927c31
#EXT-X-KEY:METHOD=AES-128,URI="https://play.qiqiuyun.net/sdk_api/video/hls_clef/sd?resNo=cf5e9390005b47a6b8cc5ef971927c31&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsZXZlbCI6InNkIiwicGxheUF1ZGlvIjpudWxsLCJubyI6ImNmNWU5MzkwMDA1YjQ3YTZiOGNjNWVmOTcxOTI3YzMxIiwianRpIjoiNzljMTMyZTYtOTI1YS00MiIsInRpbWVzIjoxLCJleHAiOjE2NjQzNjM4MjQsImVuY3J5cHQiOjIsIm5hdGl2ZSI6MCwiaGxzQ2xlZkVuY3J5cHRWZXJzaW9uIjozfQ.-K3v_ZMMzLPjd2Lmu3geP-b9NEj-KvbyPNAY4MMDZps&ssl=1",IV=0xae131c539df5aefa7ca3a33bab83dd93
#EXTINF:10.000,
https://ese3a9b6c5d0ic-pub.pubssl.qiqiuyun.net/39650/cf5e9390005b47a6b8cc5ef971927c31/ljpioMlOykKFpOC1-merged-sd_seg_2_ehls_646237?schoolId=39650&fileGlobalId=cf5e9390005b47a6b8cc5ef971927c31
#EXT-X-KEY:METHOD=AES-128,URI="https://play.qiqiuyun.net/sdk_api/video/hls_clef/sd?resNo=cf5e9390005b47a6b8cc5ef971927c31&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsZXZlbCI6InNkIiwicGxheUF1ZGlvIjpudWxsLCJubyI6ImNmNWU5MzkwMDA1YjQ3YTZiOGNjNWVmOTcxOTI3YzMxIiwianRpIjoiNzljMTMyZTYtOTI1YS00MiIsInRpbWVzIjoxLCJleHAiOjE2NjQzNjM4MjQsImVuY3J5cHQiOjIsIm5hdGl2ZSI6MCwiaGxzQ2xlZkVuY3J5cHRWZXJzaW9uIjozfQ.-K3v_ZMMzLPjd2Lmu3geP-b9NEj-KvbyPNAY4MMDZps&ssl=1",IV=0x6a911581c945bec939aec369a254c8eb
#EXTINF:10.000,
https://ese3a9b6c5d0ic-pub.pubssl.qiqiuyun.net/39650/cf5e9390005b47a6b8cc5ef971927c31/ljpioMlOykKFpOC1-merged-sd_seg_3_ehls_6e1428?schoolId=39650&fileGlobalId=cf5e9390005b47a6b8cc5ef971927c31
#EXT-X-KEY:METHOD=AES-128,URI="https://play.qiqiuyun.net/sdk_api/video/hls_clef/sd?resNo=cf5e9390005b47a6b8cc5ef971927c31&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsZXZlbCI6InNkIiwicGxheUF1ZGlvIjpudWxsLCJubyI6ImNmNWU5MzkwMDA1YjQ3YTZiOGNjNWVmOTcxOTI3YzMxIiwianRpIjoiNzljMTMyZTYtOTI1YS00MiIsInRpbWVzIjoxLCJleHAiOjE2NjQzNjM4MjQsImVuY3J5cHQiOjIsIm5hdGl2ZSI6MCwiaGxzQ2xlZkVuY3J5cHRWZXJzaW9uIjozfQ.-K3v_ZMMzLPjd2Lmu3geP-b9NEj-KvbyPNAY4MMDZps&ssl=1",IV=0x2eed01d1914223f5f53208171b7dcc6f
#EXTINF:10.000,
https://ese3a9b6c5d0ic-pub.pubssl.qiqiuyun.net/39650/cf5e9390005b47a6b8cc5ef971927c31/ljpioMlOykKFpOC1-merged-sd_seg_4_ehls_ae5759?schoolId=39650&fileGlobalId=cf5e9390005b47a6b8cc5ef971927c31
#EXT-X-KEY:METHOD=AES-128,URI="https://play.qiqiuyun.net/sdk_api/video/hls_clef/sd?resNo=cf5e9390005b47a6b8cc5ef971927c31&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsZXZlbCI6InNkIiwicGxheUF1ZGlvIjpudWxsLCJubyI6ImNmNWU5MzkwMDA1YjQ3YTZiOGNjNWVmOTcxOTI3YzMxIiwianRpIjoiNzljMTMyZTYtOTI1YS00MiIsInRpbWVzIjoxLCJleHAiOjE2NjQzNjM4MjQsImVuY3J5cHQiOjIsIm5hdGl2ZSI6MCwiaGxzQ2xlZkVuY3J5cHRWZXJzaW9uIjozfQ.-K3v_ZMMzLPjd2Lmu3geP-b9NEj-KvbyPNAY4MMDZps&ssl=1",IV=0x446753ae47925cb1a02271150bcb0687
#EXTINF:10.000,
https://ese3a9b6c5d0ic-pub.pubssl.qiqiuyun.net/39650/cf5e9390005b47a6b8cc5ef971927c31/ljpioMlOykKFpOC1-merged-sd_seg_5_ehls_975bb9?schoolId=39650&fileGlobalId=cf5e9390005b47a6b8cc5ef971927c31
#EXT-X-KEY:METHOD=AES-128,URI="https://play.qiqiuyun.net/sdk_api/video/hls_clef/sd?resNo=cf5e9390005b47a6b8cc5ef971927c31&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsZXZlbCI6InNkIiwicGxheUF1ZGlvIjpudWxsLCJubyI6ImNmNWU5MzkwMDA1YjQ3YTZiOGNjNWVmOTcxOTI3YzMxIiwianRpIjoiNzljMTMyZTYtOTI1YS00MiIsInRpbWVzIjoxLCJleHAiOjE2NjQzNjM4MjQsImVuY3J5cHQiOjIsIm5hdGl2ZSI6MCwiaGxzQ2xlZkVuY3J5cHRWZXJzaW9uIjozfQ.-K3v_ZMMzLPjd2Lmu3geP-b9NEj-KvbyPNAY4MMDZps&ssl=1",IV=0x4879c23437d1998b6cd598c2021eb723
#EXTINF:10.000,

**Comment by Momo707577045** [comment]
无权限访问呢，需要留一下视频播放网站才可以查看问题哦

**Comment by Momo707577045** [comment]
问题应该已经解决了，在试试看看
