### ISSUE TITLE
在微博搜索页点开评论会报错

### ISSUE THREAD

**Issue by zhoufenfens** [Momo707577045/m3u8-downloader#88]
例如这个链接  [微博热搜-闹钟没响](https://s.weibo.com/weibo?q=%E9%97%B9%E9%92%9F%E6%B2%A1%E5%93%8D)
点击展开评论区域的时候
控制台报错
<img width="525" alt="image" src="https://user-images.githubusercontent.com/3303836/194709890-b26f49b0-08f8-4f46-962a-bc56035fe6c2.png">
点进去看是这里出现问题
<img width="486" alt="image" src="https://user-images.githubusercontent.com/3303836/194709930-ef9e00e7-b8a4-44fa-aa93-2f50c6a6b53c.png">

**Comment by Momo707577045** [comment]
感谢回复，还附上代码截图，有心了。
问题已修复，点击以下链接以更新插件
https://blog.luckly-mjw.cn/tool-show/m3u8-downloader/m3u8-downloader.user.js
