### ISSUE TITLE
"跳转下载"标题处理还是有问题

### ISSUE THREAD

**Issue by Eunknight** [Momo707577045/m3u8-downloader#89]

**Comment by Eunknight** [comment]
因为链接带了多余的title，所以下载失败。会**报错**：”链接不正确，请查看链接是否有效“
参考 https://github.com/Momo707577045/m3u8-downloader/pull/87/files （这个代码会导致title失效）
``` javascript
// 这个代码处理不对 会截到title
this.url = href.split('?source=')[1]
```

严格定义这几个变量和使用吧

- href 浏览器链接，包含 source 和 title
- source 传过来的下载链接 
- title 传过来的页面标题
- 输入框显示和输入的链接
- 下载（中）的链接
- this.url ？？？ 代码里这应该是贯穿整个代码的视频链接，但是赋值时机、title处理、手动输入时下载处理没看懂。

最后处理好用户输入的，显示的，下载的，修改链接这个代码关系
相关代码`History.replaceState()`

作者不处理pull requests，也不同意，也不拒绝，只能留言了。如果作者留言，我愿意改代码提 pull requests。

**Comment by Eunknight** [comment]
因为链接带了多余的title，所以下载失败。会**报错**：”链接不正确，请查看链接是否有效“
参考 https://github.com/Momo707577045/m3u8-downloader/pull/87/files （这个代码会导致网页链接的title消失，title参数失效，作者有不处理，我自己关了）

// 这个代码处理不对 会截到title
this.url = href.split('?source=')[1]
严格定义这几个变量和使用吧

href 浏览器链接，包含 source 和 title
source 传过来的下载链接
title 传过来的页面标题
输入框显示和输入的链接
下载（中）的链接
this.url ？？？ 代码里这应该是贯穿整个代码的视频链接，但是赋值时机、title处理、手动输入时下载处理没看懂。
最后处理好用户输入的，显示的，下载的，修改链接这几个代码的关系
相关代码History.replaceState()

作者不处理pull requests，也不同意，也不拒绝，只能留言了。如果作者留言，我愿意改代码提 pull requests。

**Comment by Momo707577045** [comment]
方便留一下测试用例吗，那个页面会触发这个bug 呢？
我周六修复过这个问题，用你的用例试试看还有没有问题

**Comment by Eunknight** [comment]
重新更新了一下插件，现在没问题了，不折腾了。

我重新看了一下代码，& -> ? ，变成了get请求的参数。然后大多数应该不处理请求里的未定义参数，然后就没问题了。（手动捂脸）。代码不严谨。但我没影响了，应该对大部分人也没影响。

其他无关紧要的：
- 外部插件，Tampermonkey 不自动更新，除非单独设置。（解决方法：1.发到greasyfork。2.保存插件变量，一定间隔请求源文件，判断版本号，通知有新版本）
- 随便试的时候，有个m3u8链接带参数，跳转的时候就直接没了title。（解决方法：优化代码）（611行 `url: this.url,` 这里获取 .ts文件列表，只要这里处理好应该会没问题吧)
