### ISSUE TITLE
资源为空，请查看链接是否有效

### ISSUE THREAD

**Issue by kevinriver** [Momo707577045/m3u8-downloader#9]
http://v.taizhou.com.cn/share/OuYf8x26i24jV2cQ
从f12来看每次的m3u8的地址都是变得，我取刷新页面后最新得m3u8地址，显示资源为空
我装了另一个能播放m3u8的扩展，它是可以播放提取到的m3u8地址的，但是它不能另存为
请问怎么解决资源为空的问题？

**Comment by Momo707577045** [comment]
抱歉，工作忙，未能及时回复。可以加我 qq 详聊，有些信息需要了解
