### ISSUE TITLE
在某视频网站上无法加载会视频

### ISSUE THREAD

**Issue by zhoufenfens** [Momo707577045/m3u8-downloader#91]
你好，在 https://shuoqiudi.com  这个网站上如果打开了插件，会造成播放器工作不正常，播放不了视频，关掉插件就正常了，能关注下这个问题吗？

**Comment by Momo707577045** [comment]
链接失效了，有其他链接遇到类似的情况吗

**Comment by zhoufenfens** [comment]
随便选择一场比赛进去，例如 这个 https://shuoqiudi.com/player/2/1/0/3671544
