### ISSUE TITLE
反馈特定链接失效

### ISSUE THREAD

**Issue by YXy1986** [Momo707577045/m3u8-downloader#92]
下面的链接下载失败。https://pri-cdn-tx.xiaoeknow.com/app8oKNHzl85461/private_index/166521882549dnNR.m3u8?sign=37d706171ca6ac4ad63c37ac60656b4a&t=636c5855

**Comment by Momo707577045** [comment]
您未获授权，无法查看此网页。
需要提供视频所在地址，以便测试

**Comment by YXy1986** [comment]
https://app8oknhzl85461.pc.xiaoe-tech.com/detail/p_63412c81e4b0eca59c3aa629/6?product_id=p_63412c81e4b0eca59c3aa629




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月17日(星期四) 下午3:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Momo707577045/m3u8-downloader] 反馈特定链接失效 (Issue #92)





 
您未获授权，无法查看此网页。
 需要提供视频所在地址，以便测试
