### ISSUE TITLE
加密的视频就没办法了么

### ISSUE THREAD

**Issue by jackbauer007007** [Momo707577045/m3u8-downloader#93]
腾讯课堂的视频,提示<视频已进行定制化加密，不提供定制化解密下载>,这种还有办法么

**Comment by Momo707577045** [comment]
可以试试无差别视频提取工具
https://segmentfault.com/a/1190000025182822?utm_source=sf-similar-article

**Comment by jackbauer007007** [comment]
无差别视频提取工具,不是生成一个视频文件,一个音频文件么,我想到一个办法不需要合并视频,生成一个网页文件播放,用video标签,和audio标签,监听video的进度,改变audio的进度,这样就同步了,怎么样

**Comment by jackbauer007007** [comment]
<video id="video" style="width: 1000px;height: 500px;" src="a.mp4" controls></video>
		<audio id="audio" src="a_audio.mp3" controls></audio>
		
		<script>
			movie.addEventListener("timeupdate", function() {
				var currentTime = movie.currentTime;
			    shengyin.currentTime = currentTime;
			}, false);
		</script>
