### ISSUE TITLE
能批量下载吗

### ISSUE THREAD

**Issue by 112292454** [Momo707577045/m3u8-downloader#96]
从网址https://blog.luckly-mjw.cn/tool-show/m3u8-downloader/index.html来的
能批处理吗，就是像迅雷的，可以粘贴多个链接一起下载；以及简单的过一下正则，匹配到http开头。
不行的话过段时间我自己java写一下用，自己关这个）

**Comment by dfjeiwn** [comment]
[m3u8 downloader](https://streamfab.com/drm-m3u8-downloader.htm) 这个软件可以批量下载，有免费试用，你可以看看。
