### ISSUE TITLE
建议在网页顶端新增下载进度

### ISSUE THREAD

**Issue by XTLdirector** [Momo707577045/m3u8-downloader#98]
在注入下载的时候就不用翻到最底下查看是否下载完了，尤其是同时下载多个网页上的视频的时候

**Comment by Momo707577045** [comment]
![image](https://user-images.githubusercontent.com/12947294/218015128-11095b1d-67e3-4935-859f-e46c34c8832e.png)
感谢反馈，顶部有进度显示的哈

**Comment by XTLdirector** [comment]
我的意思是在网页的顶端（仅针对注入下载模式），目前这个情况还要下滑到页面最底下查看。如果能在网页最上面显示进度而不用手动下滑到底下，这样更方便高效
