### ISSUE TITLE
油猴开启m3u8-downloader，油管视频不能播放

### ISSUE THREAD

**Issue by fe6520** [Momo707577045/m3u8-downloader#99]
1.油猴开启m3u8-downloader，油管视频不能播放，表现为播放窗口一直转圈（出现次数多些）或者白屏。其它区域显示正常。
2.油猴关闭m3u8-downloader后，再刷新视频页面，可以正常播放。
3.目前解决办法，把// @exclude      https://www.youtube.com/*添加到脚本中。

**Comment by Momo707577045** [comment]
更新脚本试试看，我这边复现不了哦
https://blog.luckly-mjw.cn/tool-show/m3u8-downloader/m3u8-downloader.user.js
